### PR TITLE
wgpu base changes

### PR DESCRIPTION
**Pull request by guusw**
Base changes without adding any wgpu sources:
- Remove BGFX
- Remove graphics tests & things that depend on it (input/imgui/gizmos)
- Bump submodules
- Some minor workflow/code changes

### CODE REVIEW

**Comment by Kryptos-FR** [comment]
I'd rather not merge that PR since it removes some files. And as we are working on the documentation, it will create conflicts between the merge of this PR and before the merge of the final one.

**Comment by guusw** [comment]
@Kryptos-FR I tried to split up removing BGFX from adding the new code. Thinking we can squash this later.
This might make it a bit easier to review the other PR as there are less removed file changes

**Comment by Kryptos-FR** [comment]
> @Kryptos-FR I tried to split up removing BGFX from adding the new code. Thinking we can squash this later. This might make it a bit easier to review the other PR as there are less removed file changes

In that case, what we can do is retarget PR #162 to be merged on this branch instead of `devel`. That way, it will "ignore" all the commits that are here (since that will be the new base) and "hide" the removed files. That will hopefully make it easier to review.

Then when everything is ready, we either retarget again to `devel` or we first merge into that PR's branch and merge that PR as a final step. In a sense, it is like having an "epic" PR/branch.

**Comment by guusw** [comment]
@Kryptos-FR I kept the files that have documentation (imgui/input/XR/gizmos) in this PR so it should not cause tree conflicts later on.

**Comment by guusw** [comment]
@sinkingsugar @Kryptos-FR Will mark these as reviewed and merge to wgpu-stable if you approve.

**Review by sinkingsugar — APPROVED** [review]

**Comment by sinkingsugar** [comment]
Good for me, XR files are preserved right?
Also I see some failures in CI.

**Comment by guusw** [comment]
Yeah, they're all left as-is but disabled until they get fixed up to work with the new graphics.

**Pull request closed without merging**
